### ISSUE TITLE
When last word of decode contains number

### ISSUE THREAD

**Issue by YaaseenIbrahim** [YaaseenIbrahim/Caesar-Encryption#13]
_**All possible scenarios that ive tested will be stated here, please bear with me. All scenarios are referring to entering in decode method NOT encode method**_

**Terminology to be noted:**
- First round means the first time you enter something
- Second round means if you press Y to repeat again
- So on and so forth for the rounds

### When you put last word as ALL NUMBERS in first round
**Testdata**: 'ehehehe 2323'
**Result:** Error
If its first time entering and u are asked to enter message and you write something like 'ehehehehh 23232' it throws an error. This is because of this section of code (line 130 or so):
`for i in enterStep:
                if i in alphabet:
                    encodedStepString += str(alphabet.index(i))
                    step = int(encodedStepString) * -1
            stepForAlphabet = step % 26`
Obviously none of the i is in alphabet so step wont actually get a value. So stepForAlphabet is the one that throws the error as step % 26 cant happen since step doesnt have a value

### When you put NUMBERS AND LETTERS MIXED in first round
**Result: No error**
For something like "ehehehehe 23sjdj231", it only uses the 'sjdj' part and decodes it. No error is made. This is also because of that line 130 code, because step can only be said if the last word has letters.

More example (first round btw):
dolp d - outputs alim
dolp 2382892d2139293- also outputs alim

This seems not much of an issue rn but it gets worse on other rounds, plus it is upto discussion whether we should tell the user 'yo there is a num in last word' or we just use the letter part in last word and not say anything to user. Please refer to this discussion point if replying

### When you do NUMBERS AND LETTERS MIXED in first round then ALL NUMBERS in second round
**Testdata**: 'dolp 232d434'
**Result:** alim
Repeat?: Y
Testdata: dolp 23232323
result: alim

So here the step variable has 'd' stored from first round. Since there is all numbers in 2nd round, the step doesnt get changed so step still has 'd'. Which is used to decode the 2nd testdata, even tho we never entered 'd' as a step for the 2nd thing.

###  When you do NUMBERS AND LETTERS MIXED in first round then NUMBERS AND LETTERS MIXED in second round
_Same as when you do NUMBERS AND LETTERS MIXED in first round only_

## Solutions
We need to implement the number checker. I think we must output "bro u messed up" if the last word has any nums in it, instead of just using the non-num part as step. Because it seems like, if we do that way then step will forever be that. Ofcourse we could check if last word is only numbers, and if it is then give error, otherwise just keep going and use the non-num part of step. Please refer which opinion u think is best

**Comment by Aiman-Adam** [comment]
### **Replying to: When you put last word as ALL NUMBERS in first round**:
We can easily solve this issue by doing something like the **_space check_** but with numbers. I hope that is enough for you to understand.  I am on it now and you will see the results _InshaAllah_.

### **Replying to: When you put NUMBERS AND LETTERS MIXED in first round**:
I do not think this is a big issue and it is really up for us to decide. I like the way you mentioned where the code outputs **_there are numbers in the step l_**. It is mostly a user friendly thing rather than an issue in my opinion. We can work on that as well _Biiznillahi_.

### **Replying to: When you do NUMBERS AND LETTERS MIXED in first round then ALL NUMBERS in second round**:
I think this can be easily fixed by resetting the encoded string step after the user says they want to repeat.

### **Conclusion** :
_I am going to start working on issue 1 and 3 right away. Once again, if there is a way to shorten the code, i will leave you to it. Let me know what you think of my solutions_

**Comment by YaaseenIbrahim** [comment]
Go ahead on work on it. I will have it known that those arent 3 separate issues, rather ive just stated 3 cases in which the results differ. Also i cannot tell your stance on the discussion matter just yet, so to simply do we:

1. Reject the enteredMessage if the last word contains any numbers, then tell the user to re-enter because it has numbers
2. Reject the enteredMessage if the last word contains ALL numbers, otherwise if it has any numbers then just use the letter part as encodedstep and ignore the number part and dont tell user that we ignored number part

Please state which of the 2 opinions you are of.

**Comment by Aiman-Adam** [comment]
2
